replicaCount: 1

image:
  repository: ghcr.io/vineethvijay/kube-snorlax
  tag: latest

containerPort: 8080

targetNamespace: default

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 10

persistence:
  enabled: true
  size: 64Mi
  # storageClass: ""
